from dnalib.nucleotides import NUCLEOTIDES_DNA, count_nucleotides, transcribe_to_rna


def rosalind_seq_format(seq):
    return ''.join((str(nuc) for nuc in seq))


def rosalind_count_dna(histogram):
    return ' '.join(str(histogram[n]) for n in NUCLEOTIDES_DNA)


def test_rosalind_count_dna():
    s = 'AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC'
    assert rosalind_count_dna(count_nucleotides(s)) == '20 12 17 21'


def rosalind_01():
    s = 'GGCAGGAACCCTGTCGGCTTCTCCCCCCTATACGGAAAAAAGTGTGGCAGTGGAAGAAAGACCCACTGCGTTCGGAAAAACTAGCGCTCGAACGCTCGGCAGGGTAA' \
        'CGCCTCGGACTGACAGTCTCTAGTATGTCATCCCACAAACCTGACAACGACCCTCCGGGAGAGTCCGAGTCATGAAGGGCGGGCGGCTTTAACAACATCCACTTGCA' \
        'CTGAACGCTTTAGACATGGCTTGATGCGCCAGGCCATTGCAATCTTTCTTTGCACACACATTCAGGTGGTTCTCAGTAACTGTAAACGATGAACGAGGCACGCGGTT' \
        'CATGATGGTTGCGTGGCAGTATAAAAAACTTAAACGTTCGAAAGGGAGATTTGGTTCGCGTCGCCACGTGCGCGGTATGCGGCTAAACGGCAGACGAACATACTCTT' \
        'AGATGCTTTTAGAATCCGGACTAGTATTGCCTGGTATACTGGTGATAGGAGCAGTGCAGTTAGTGTTACCAAAATCACTCACTTCTAAGCCGAGTGTCGGTAAACAG' \
        'CACACATGATATCCATGGGCATATTAGCAAGGTCGGACGGGTACCAAGAAAAGTAAGGTGCGTGCCATCAAATTACTGTTTATCGGGTCAGAGATTCTAATGCATGT' \
        'TGCGAGGCATGTACTCAACTGTCTTGAGTGGCCAGGATTTGAGGTTGACGAGGGCCTGAAAAATTGTGAGCTTGGTGGGAAGAGAGAGAAGGAGGAGTTCTATTCTG' \
        'CATCATGCGGCATCCTCCAGGAGTTCCCGCAATATTTAGTAGGGCGGTCCGGTAGCCCGCTAAGAGACGCCTGAGTGACAGAAATCATGGACGCCCGGCGCGTCACT' \
        'ATTAACTAATTAGCTGCATAAGATCGAGCGGACCGTGACGATAAGATCGAAGATGTGAGCTTTCTAAAACAGTGGGGCGGACTTCACGTTTCGAGCGCTGGGCCA'
    print(rosalind_count_dna(count_nucleotides(s)))


def rosalind_02():
    s = 'AGCAGTGCGGTCTCGGGCCGGCTTGGCTGTCTCGACCGATGTGCGCTCATGCGCGTCGAATGATGATGATACACGTGTTTGACAATTTGTATTCATTAGTTCTGAGC' \
        'GAACATTCGTGACGGCGCGGAGTAGCCGGATTAATACTACGTAGTCCCAGTGGTTCGTCGCGGGAGTCCATCAGCGGCAGATACCCGTAGGAAAGCGCTCGTTACGG' \
        'TTTGGGCATCCCCCAGACATCTCCGCACCCTGGCCAAGTGGGAACGCCCGTGACTCGCCTTCGCTCGTGGAAGAGCGATAGTTTTTGGTTACAGGTTATTGATTCCG' \
        'CATGCACCACGTCCGCTCCACAGAAAGCTTCTACTGCTCGTGCGTTAGACTGCCTCTGGGATGTGACAGATTCGACGGTGACGTAAATGGGACCGCTATAACAAATA' \
        'AGGATTAGATGAGATCCGATCTCGTGCGGACTGATCCGACCTCGCCATCACGGCAAGGAGCTAGCCGTGGTCTCTAGTCCTCCACGATCAGTGTTCAATGTGTTGCG' \
        'GAACGTACTGCGGCCCAAGTCGGTGCGCTTATCGGATTATCGCGCTACCCAAGCTGGTAGTTAGGACCAGGATGGTCATATTCGGTCATACAAGATGATGATACCGC' \
        'AGGCCCAAACCATTCCGATAGAAGCGTAGTCGCGGTGGAGTGCCGTGTACATTCAAGGATCACACGCTGCACATTATATCGCTGAAGCCCACGAAAAAAAATAGCGC' \
        'CCCGGACGTAGCGAGCCGTATGCCATTCCTTTCCGTGTGCTAGCCCCCATGAGTTTAGGTCACTGCCCCCAATCGCGCTTTCAGGCTAGTATCAGTTAAGCCACTAA' \
        'ACGTGGACACCTACTCTGTCACCATCATTGCTTGGAGAGTTAGATGGGGCCAGGAGCAATTAAATATTGCCGCTAGCCACCATTAACACGAGCCTTACTATTTACT'
    print(rosalind_seq_format(transcribe_to_rna(s)))


if __name__ == '__main__':
    rosalind_02()
