from dnalib.nucleotides import \
    NUCLEOTIDES_DNA, \
    seq_to_str, \
    str_to_dna, \
    count_nucleotides, \
    transcribe_to_rna, \
    reverse_complement_dna


def rosalind_DNA():
    def rosalind_count_dna(histogram):
        return ' '.join(str(histogram[n]) for n in NUCLEOTIDES_DNA)

    s = 'GGCAGGAACCCTGTCGGCTTCTCCCCCCTATACGGAAAAAAGTGTGGCAGTGGAAGAAAGACCCACTGCGTTCGGAAAAACTAGCGCTCGAACGCTCGGCAGGGTAA' \
        'CGCCTCGGACTGACAGTCTCTAGTATGTCATCCCACAAACCTGACAACGACCCTCCGGGAGAGTCCGAGTCATGAAGGGCGGGCGGCTTTAACAACATCCACTTGCA' \
        'CTGAACGCTTTAGACATGGCTTGATGCGCCAGGCCATTGCAATCTTTCTTTGCACACACATTCAGGTGGTTCTCAGTAACTGTAAACGATGAACGAGGCACGCGGTT' \
        'CATGATGGTTGCGTGGCAGTATAAAAAACTTAAACGTTCGAAAGGGAGATTTGGTTCGCGTCGCCACGTGCGCGGTATGCGGCTAAACGGCAGACGAACATACTCTT' \
        'AGATGCTTTTAGAATCCGGACTAGTATTGCCTGGTATACTGGTGATAGGAGCAGTGCAGTTAGTGTTACCAAAATCACTCACTTCTAAGCCGAGTGTCGGTAAACAG' \
        'CACACATGATATCCATGGGCATATTAGCAAGGTCGGACGGGTACCAAGAAAAGTAAGGTGCGTGCCATCAAATTACTGTTTATCGGGTCAGAGATTCTAATGCATGT' \
        'TGCGAGGCATGTACTCAACTGTCTTGAGTGGCCAGGATTTGAGGTTGACGAGGGCCTGAAAAATTGTGAGCTTGGTGGGAAGAGAGAGAAGGAGGAGTTCTATTCTG' \
        'CATCATGCGGCATCCTCCAGGAGTTCCCGCAATATTTAGTAGGGCGGTCCGGTAGCCCGCTAAGAGACGCCTGAGTGACAGAAATCATGGACGCCCGGCGCGTCACT' \
        'ATTAACTAATTAGCTGCATAAGATCGAGCGGACCGTGACGATAAGATCGAAGATGTGAGCTTTCTAAAACAGTGGGGCGGACTTCACGTTTCGAGCGCTGGGCCA'
    print(rosalind_count_dna(count_nucleotides(str_to_dna(s))))


def rosalind_RNA():
    s = 'AGCAGTGCGGTCTCGGGCCGGCTTGGCTGTCTCGACCGATGTGCGCTCATGCGCGTCGAATGATGATGATACACGTGTTTGACAATTTGTATTCATTAGTTCTGAGC' \
        'GAACATTCGTGACGGCGCGGAGTAGCCGGATTAATACTACGTAGTCCCAGTGGTTCGTCGCGGGAGTCCATCAGCGGCAGATACCCGTAGGAAAGCGCTCGTTACGG' \
        'TTTGGGCATCCCCCAGACATCTCCGCACCCTGGCCAAGTGGGAACGCCCGTGACTCGCCTTCGCTCGTGGAAGAGCGATAGTTTTTGGTTACAGGTTATTGATTCCG' \
        'CATGCACCACGTCCGCTCCACAGAAAGCTTCTACTGCTCGTGCGTTAGACTGCCTCTGGGATGTGACAGATTCGACGGTGACGTAAATGGGACCGCTATAACAAATA' \
        'AGGATTAGATGAGATCCGATCTCGTGCGGACTGATCCGACCTCGCCATCACGGCAAGGAGCTAGCCGTGGTCTCTAGTCCTCCACGATCAGTGTTCAATGTGTTGCG' \
        'GAACGTACTGCGGCCCAAGTCGGTGCGCTTATCGGATTATCGCGCTACCCAAGCTGGTAGTTAGGACCAGGATGGTCATATTCGGTCATACAAGATGATGATACCGC' \
        'AGGCCCAAACCATTCCGATAGAAGCGTAGTCGCGGTGGAGTGCCGTGTACATTCAAGGATCACACGCTGCACATTATATCGCTGAAGCCCACGAAAAAAAATAGCGC' \
        'CCCGGACGTAGCGAGCCGTATGCCATTCCTTTCCGTGTGCTAGCCCCCATGAGTTTAGGTCACTGCCCCCAATCGCGCTTTCAGGCTAGTATCAGTTAAGCCACTAA' \
        'ACGTGGACACCTACTCTGTCACCATCATTGCTTGGAGAGTTAGATGGGGCCAGGAGCAATTAAATATTGCCGCTAGCCACCATTAACACGAGCCTTACTATTTACT'
    print(seq_to_str(transcribe_to_rna(str_to_dna(s))))


def rosalind_REVC():
    s = 'GCACGCGTCGACGTGATGCGTTTCTGCACCTAAATAACCTCTTCTGAACCATTTGGGTCATGGGGCGTACACCTGTGGCCTAGATAGCATAAGAAGCATCCGGCAAA' \
        'ACAAAATAACCCTTCTTCTGAGGATACCGGAAAAGCAGCCAACAGTTTATGAAGGTAGCCCGATTCTAGAATTGAATCCTCTCTTGACATGAAATAGAGCCGTGTGC' \
        'GCGGCTCAAAACCCACTTGGAGACAGAGGCGCGACTTGTAGTTTTATGTCAAATCTGACTGTATCAAGGTCGTCTTGACCGTAGGTATAGAAAGCGAGAAGGTAATT' \
        'CCGCGGATGCGCTTTGGTGTACCGTAAATTCACCCCCTTGCAATGAACACAGATATTTGCATAGTGCAACCTCGTTGTCCGAGTCGTAAGCCATTGACTAGCTTCAC' \
        'TTGAAACGGGCCCCCCTGCACTTCCCATATGAACAATCTGGTCATGTTTTTCCACCGTTTGGGATTCCTGATATTATACGCGAATCCGCTCGGTGTGGCTGATGCGA' \
        'ACGTAGTAGAAACACATGGCACGCTTGAAACAGCCCATATTGGTTCGTGGCATTCATGTTCGCCTAGATATCACTATTTGGAACAATCACCCGCTTCTCTTCGGCAG' \
        'GACTACTTAATGTAAAAAGCGGTCGAAATGCGCCTCACATGACTGCAGCACGGGCAGCTCGCCTGGACCGGCGGGGCTAACGTTGTGCGTGTTACATCAACAACAGC' \
        'TGCAGAGAAAACAGACCATGATTAAGCCGGCCCCGGGCTTATATGTGATGTGTGCGATCGTTTAGCACCTGAGTCTAAATTTTACATCCTAAACATTAGCTCAGCGC' \
        'ATTTGGCCAATCTGTAGATGGGTTACACTTGTTCCGCCAGACCGGCGCATCCAGGGTTACTACGCCTCTC'
    dna_forward = str_to_dna(s)
    dna_reverse = reverse_complement_dna(dna_forward)
    print(seq_to_str(dna_reverse))


def rosalind_FIB():
    bunnies = [1, 1]
    n = 31
    k = 5
    for i in range(n - 2):
        # [-2]*k : because pregnancy lasts one month, bunnies of two months ago give birth, each to k bunny pairs.
        # [-1]: those are babies, they'll be adults next month.
        x = bunnies[-2] * k + bunnies[-1]
        bunnies.append(x)
    print(bunnies)


if __name__ == '__main__':
    rosalind_FIB()
